version: 2
workflows:
  single-simple:
    steps:
      - name: openvino-pipeline
        command: experiment.run_single_node
        paramsFile: .ps_project/managed.yaml
    triggers:
        branches:
            only: .*
        tags:
            only:
            - v.*
            - latest
    checks: #[optional]
        custom:MSE:
            target: "0.0..0.5"
            aggregate: "mean"
        defaults: #[optional]
            precision: 3