version: 2
workflows:
  single-simple:
    steps:
      - name: openvino-pipeline
        command: experiment.run_single_node
        paramsFile: .ps_project/managed.yaml
        checks: #[optional]
          custom:MSE:
             target: "0.0..0.5"
             aggregate: /MSE
          defaults: #[optional]
              precision: 3
    triggers:
        branches:
          only: .*
        tags:
          only:
            - v.*
            - latest
