version: 2
workflows:
  single-simple:
    steps:
      - name: openvino-pipeline
        command: experiment.run_single_node
        paramsFile: .ps_project/managed.yaml
        checks: #[optional]
          custom:accuracy:
             target: "0.98..1"
             aggregate: /result/max
          defaults: #[optional]
              precision: 3
    triggers:
        branches:
          only: .*
        tags:
          only:
            - v.*
            - latest
